export const mockImages = [
  {
    albumId: 1,
    id: 1,
    title: 'accusamus beatae ad facilis cum similique qui sunt',
    url: 'https://via.placeholder.com/600/92c952',
    thumbnailUrl: 'https://via.placeholder.com/150/92c952',
  },
  {
    albumId: 1,
    id: 2,
    title: 'reprehenderit est deserunt velit ipsam',
    url: 'https://via.placeholder.com/600/771796',
    thumbnailUrl: 'https://via.placeholder.com/150/771796',
  },
  {
    albumId: 1,
    id: 3,
    title: 'officia porro iure quia iusto qui ipsa ut modi',
    url: 'https://via.placeholder.com/600/24f355',
    thumbnailUrl: 'https://via.placeholder.com/150/24f355',
  },
  {
    albumId: 1,
    id: 4,
    title: 'culpa odio esse rerum omnis laboriosam voluptate repudiandae',
    url: 'https://via.placeholder.com/600/d32776',
    thumbnailUrl: 'https://via.placeholder.com/150/d32776',
  },
  {
    albumId: 1,
    id: 5,
    title: 'natus nisi omnis corporis facere molestiae rerum in',
    url: 'https://via.placeholder.com/600/f66b97',
    thumbnailUrl: 'https://via.placeholder.com/150/f66b97',
  },
  {
    albumId: 1,
    id: 6,
    title: 'accusamus ea aliquid et amet sequi nemo',
    url: 'https://via.placeholder.com/600/56a8c2',
    thumbnailUrl: 'https://via.placeholder.com/150/56a8c2',
  },
  {
    albumId: 1,
    id: 7,
    title: 'officia delectus consequatur vero aut veniam explicabo molestias',
    url: 'https://via.placeholder.com/600/b0f7cc',
    thumbnailUrl: 'https://via.placeholder.com/150/b0f7cc',
  },
  {
    albumId: 1,
    id: 8,
    title: 'aut porro officiis laborum odit ea laudantium corporis',
    url: 'https://via.placeholder.com/600/54176f',
    thumbnailUrl: 'https://via.placeholder.com/150/54176f',
  },
  {
    albumId: 1,
    id: 9,
    title: 'qui eius qui autem sed',
    url: 'https://via.placeholder.com/600/51aa97',
    thumbnailUrl: 'https://via.placeholder.com/150/51aa97',
  },
  {
    albumId: 1,
    id: 10,
    title: 'beatae et provident et ut vel',
    url: 'https://via.placeholder.com/600/810b14',
    thumbnailUrl: 'https://via.placeholder.com/150/810b14',
  },
  {
    albumId: 1,
    id: 11,
    title: 'nihil at amet non hic quia qui',
    url: 'https://via.placeholder.com/600/1ee8a4',
    thumbnailUrl: 'https://via.placeholder.com/150/1ee8a4',
  },
  {
    albumId: 1,
    id: 12,
    title: 'mollitia soluta ut rerum eos aliquam consequatur perspiciatis maiores',
    url: 'https://via.placeholder.com/600/66b7d2',
    thumbnailUrl: 'https://via.placeholder.com/150/66b7d2',
  },
  {
    albumId: 1,
    id: 13,
    title: 'repudiandae iusto deleniti rerum',
    url: 'https://via.placeholder.com/600/197d29',
    thumbnailUrl: 'https://via.placeholder.com/150/197d29',
  },
  {
    albumId: 1,
    id: 14,
    title: 'est necessitatibus architecto ut laborum',
    url: 'https://via.placeholder.com/600/61a65',
    thumbnailUrl: 'https://via.placeholder.com/150/61a65',
  },
]

export const mockPosts = [
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 1,
    title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
    body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
  },
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 2,
    title: 'qui est esse',
    body: 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla',
  },
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 3,
    title: 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
    body: 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut',
  },
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 4,
    title: 'eum et est occaecati',
    body: 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit',
  },
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 5,
    title: 'nesciunt quas odio',
    body: 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque',
  },
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 6,
    title: 'dolorem eum magni eos aperiam quia',
    body: 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae',
  },
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 7,
    title: 'magnam facilis autem',
    body: 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas',
  },
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 8,
    title: 'dolorem dolore est ipsam',
    body: 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae',
  },
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 9,
    title: 'nesciunt iure omnis dolorem tempora et accusantium',
    body: 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas',
  },
  {
    userId: 1,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 10,
    title: 'optio molestias id quia eum',
    body: 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error',
  },
  {
    userId: 2,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 11,
    title: 'et ea vero quia laudantium autem',
    body: 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi',
  },
  {
    userId: 2,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 12,
    title: 'in quibusdam tempore odit est dolorem',
    body: 'itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio',
  },
  {
    userId: 2,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 13,
    title: 'dolorum ut in voluptas mollitia et saepe quo animi',
    body: 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam',
  },
  {
    userId: 2,
    author: 'Teste for Teste Com',
    views: 2233,
    category: 'Programação',
    tags: ['Java', 'Eclipse'],
    id: 14,
    title: 'voluptatem eligendi optio',
    body: 'fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum',
  },
]
